import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
// function calls on the smart contracts : import them here
import {
  DataFeed, DataFeedV2, DataFeedV3, DexProp, DexPools, Pools
} from '../components/contract';

/*
export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header style={{ padding: '1rem' }}>
        <ConnectButton />
      </header>

      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
      <b>Razor Oracle:</b>
       <DataFeed />

       <DataFeedV2 />

       <DataFeedV3 />

       <DexProp />
       
      </main>
    </div>
  );
}
*/
export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header style={{ padding: '1rem' }}>
        <ConnectButton />
      </header>

      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
      
       <DexProp />
       <DexPools />
     <Pools />

      </main>
    </div>
  );
}
